"""
core/waf_fingerprint.py
Identifie le WAF d'un site web et genere des payloads de bypass specifiques.

Usage CLI:
  python core/waf_fingerprint.py --url http://monsite.com
  python core/waf_fingerprint.py --url http://monsite.com --category xss --generate-payloads
  python core/waf_fingerprint.py --stats cloudflare
"""

import argparse
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests
except ImportError:
    print("[!] requests non installe. Lancez: pip install requests")
    raise SystemExit(1)

ROOT = Path(__file__).parent.parent.resolve()
CYBERIA_DIR = ROOT / ".cyberia"
WAF_FEEDBACK_DB = CYBERIA_DIR / "waf_feedback.db"
PAYLOAD_LAB_DB = CYBERIA_DIR / "payload_lab.db"
MEMORY_HUB_DB = CYBERIA_DIR / "memory_hub.db"
SUPERVISOR_PROMPTS = CYBERIA_DIR / "supervisor_prompts.json"

# ---------------------------------------------------------------------------
# WAF detection signatures
# Each entry: header_keys (presence), header_values (key->substring), body_strings
# ---------------------------------------------------------------------------

WAF_SIGNATURES = [
    {
        "name": "cloudflare",
        "header_keys": ["CF-Ray"],
        "header_values": {"Server": "cloudflare"},
        "body_strings": ["Cloudflare", "Ray ID", "Attention Required"],
        "confidence_base": 90,
    },
    {
        "name": "sucuri",
        "header_keys": ["X-Sucuri-ID", "X-Sucuri-Cache"],
        "header_values": {},
        "body_strings": ["Sucuri Website Firewall", "sucuri.net", "Access Denied | Sucuri"],
        "confidence_base": 90,
    },
    {
        "name": "modsecurity",
        "header_keys": [],
        "header_values": {},
        "body_strings": ["ModSecurity", "Mod_Security", "mod_security", "NOYB"],
        "confidence_base": 80,
    },
    {
        "name": "wordfence",
        "header_keys": [],
        "header_values": {},
        "body_strings": ["Wordfence", "generated by Wordfence", "wordfence.com"],
        "confidence_base": 90,
    },
    {
        "name": "imperva",
        "header_keys": ["X-Iinfo"],
        "header_values": {},
        "body_strings": ["Incapsula incident", "Request unsuccessful. Incapsula", "_Incapsula_Resource"],
        "confidence_base": 88,
    },
    {
        "name": "awswaf",
        "header_keys": ["x-amzn-requestid", "x-amz-cf-id"],
        "header_values": {},
        "body_strings": ["AWS WAF", "aws-waf"],
        "confidence_base": 85,
    },
    {
        "name": "alibaba",
        "header_keys": ["X-Powered-By-Anquanbao"],
        "header_values": {},
        "body_strings": ["Anquanbao", "anquanbao"],
        "confidence_base": 95,
    },
    {
        "name": "akamai",
        "header_keys": ["X-Check-Cacheable", "Akamai-Origin-Hop"],
        "header_values": {},
        "body_strings": ["The URL you requested has been blocked", "Reference #"],
        "confidence_base": 75,
    },
    {
        "name": "f5bigip",
        "header_keys": [],
        "header_values": {},
        "body_strings": ["The requested URL was rejected", "Your support ID is"],
        "confidence_base": 80,
    },
    {
        "name": "fortiweb",
        "header_keys": ["FORTIWAFSID"],
        "header_values": {},
        "body_strings": ["FortiWeb", "FortiGuard"],
        "confidence_base": 92,
    },
    {
        "name": "barracuda",
        "header_keys": ["barra_counter_session"],
        "header_values": {},
        "body_strings": ["Barracuda Networks", "barracuda"],
        "confidence_base": 87,
    },
]

# Payloads suspects envoyes pour provoquer une reponse du WAF
_PROBE_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1--",
    "../../../../etc/passwd",
]

# ---------------------------------------------------------------------------
# WAF-specific bypass strategies for prompt generation
# ---------------------------------------------------------------------------

WAF_BYPASS_STRATEGIES = {
    "cloudflare": {
        "xss":  "unicode normalization, mutation XSS (mXSS), DOM clobbering, template literal injection, polyglot payloads, case mixing, HTML namespace switching",
        "sqli": "comment variations (/**/, --+, #), hex encoding, whitespace substitution (TAB/newline), time-based blind SLEEP variants, scientific notation for numbers",
        "lfi":  "null byte injection, double encoding, path traversal with unicode normalization (..%c0%af), URL-encoded slashes",
        "rce":  "IFS substitution, backtick vs $() execution, hex/octal encoding, command separator variants, env variable expansion",
        "ssti": "unicode delimiters, comment bypass inside template, nested expressions, alternate engine syntax",
        "ssrf": "IP obfuscation (octal, hex, IPv6), URL scheme tricks (dict://, gopher://), DNS rebinding payloads",
    },
    "modsecurity": {
        "xss":  "HTML entity encoding, attribute injection without quotes, script fragment bypass, SVG/MathML vectors, data: URI schemes",
        "sqli": "inline comments /**/, versioned comments /*!50000*/, alternative whitespace (TAB, form-feed), BETWEEN instead of =",
        "lfi":  "URL double encoding (%252F), backslash on Windows, PHP wrappers (php://filter), null byte %00",
        "rce":  "environment variable $IFS, command substitution $(), tilde expansion, glob patterns, base64 decode exec",
        "ssti": "alternate delimiters, whitespace tricks, filter bypass with string concatenation",
        "ssrf": "localhost variants (0.0.0.0, 0x7f000001, 127.1), IPv6 ::1, encoded IP addresses",
    },
    "wordfence": {
        "xss":  "JavaScript pseudo-protocol, on* event handlers in unusual tags, CSS expression, SVG animate, HTML comments",
        "sqli": "case mixing (sElEcT), alternate encoding, MySQL-specific comments, time-based exfiltration",
        "lfi":  "file:// wrapper, phar:// deserialization, data://text triggers",
        "rce":  "PHP eval via base64, system() vs exec() vs passthru() vs shell_exec()",
        "ssti": "PHP: {${phpinfo()}}, Twig: {{7*'7'}}, Smarty: {php}echo shell_exec('id');{/php}",
        "ssrf": "WordPress XMLRPC abuse, pingback to internal, metadata endpoint fetch",
    },
    "sucuri": {
        "xss":  "obfuscated event handlers, triple encoding, JavaScript URI with whitespace, Unicode escapes \\u003cscript\\u003e",
        "sqli": "UNION SELECT with comments between keywords, CHAR() for string building, hex literals 0x41",
        "lfi":  "protocol wrappers (expect://, zip://), null byte variations, case insensitive paths on Windows",
        "rce":  "PHP short tags <?=, regex /e modifier, create_function bypass",
        "ssti": "filter bypass via __class__ chains, Python __import__('os').system",
        "ssrf": "302 redirect chains, DNS pinning bypass, alternate protocols (tftp, ldap, smtp)",
    },
    "imperva": {
        "xss":  "mutation via innerHTML, setTimeout string execution, document.write bypass, Function constructor",
        "sqli": "stacked queries, cursor-based injection, error-based with EXTRACTVALUE",
        "lfi":  "absolute paths, proc/self/environ, Apache log poisoning, session file inclusion",
        "rce":  "PHP dynamic function call $$var(), variable variables, Perl system bypass",
        "ssti": "Velocity #set and #evaluate, FreeMarker ?eval, Groovy GroovyShell",
        "ssrf": "CRLF injection in URL, SNI confusion, IPv6 zone ID bypass",
    },
    "akamai": {
        "xss":  "JSFuck, Hieroglyphy, JJEncode encoded payloads, CSP bypass via JSONP endpoints",
        "sqli": "parameterized query smuggling, second-order injection, OOB via DNS/HTTP",
        "lfi":  "PHP7 pearcmd, Nginx alias traversal, Apache SSI injection",
        "rce":  "deserialization gadgets, YAML RCE via PyYAML, Java serialization",
        "ssti": "Ruby ERB <%=system('id')%>, Python code object bytecode injection",
        "ssrf": "S3 metadata endpoint, IMDS v1 vs v2 bypass, header injection via newline",
    },
    "awswaf": {
        "xss":  "React JSX injection, Angular template injection, Vue v-html bypass, DOM via postMessage",
        "sqli": "NoSQL injection ($where, $gt, $regex), GraphQL injection, ORM-level bypass",
        "lfi":  "SSRF to Lambda metadata, ECS task metadata, EC2 IMDS at 169.254.169.254",
        "rce":  "Log4Shell JNDI variants, Spring4Shell, Struts injection, XXE with system entity",
        "ssti": "Java EL injection in Spring, Thymeleaf __${...}__::.x",
        "ssrf": "AWS metadata 169.254.169.254/latest/meta-data/, HTTP_PROXY header injection",
    },
    "unknown": {
        "xss":  "Unicode normalization, HTML entity mixing, event handler variants, SVG/MathML, polyglot XSS",
        "sqli": "comment variations, encoding bypass, UNION-based, time-based, error-based techniques",
        "lfi":  "double encoding, null byte, protocol wrappers, path normalization",
        "rce":  "command separator variants, encoding, environment variable abuse",
        "ssti": "template engine-specific syntax, comment bypass, string concatenation",
        "ssrf": "IP obfuscation, alternate protocols, redirect chains",
    },
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _init_feedback_db() -> sqlite3.Connection:
    CYBERIA_DIR.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(str(WAF_FEEDBACK_DB), timeout=10)
    con.execute("""
        CREATE TABLE IF NOT EXISTS feedback (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            url          TEXT,
            payload      TEXT,
            waf          TEXT,
            blocked      INTEGER DEFAULT 1,
            payload_type TEXT,
            timestamp    TEXT
        )
    """)
    con.execute("CREATE INDEX IF NOT EXISTS idx_fb_waf ON feedback (waf)")
    con.commit()
    return con


def _write_supervisor_prompt(entry: dict) -> None:
    if not SUPERVISOR_PROMPTS.exists():
        data: dict = {"generated_at": _now(), "priority_prompts": []}
    else:
        try:
            data = json.loads(SUPERVISOR_PROMPTS.read_text(encoding="utf-8"))
        except Exception:
            data = {"generated_at": _now(), "priority_prompts": []}

    prompts: list = data.get("priority_prompts", [])
    # Remplacer entree existante meme categorie + meme WAF
    prompts = [
        p for p in prompts
        if not (p.get("category") == entry["category"] and p.get("waf_target") == entry.get("waf_target"))
    ]
    prompts.insert(0, entry)
    data["priority_prompts"] = prompts[:20]
    data["generated_at"] = _now()
    SUPERVISOR_PROMPTS.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _inject_memory(category: str, content: str) -> None:
    if not MEMORY_HUB_DB.exists():
        return
    try:
        con = sqlite3.connect(str(MEMORY_HUB_DB), timeout=5)
        con.execute(
            "INSERT INTO memories (source, category, content, created_at) VALUES (?,?,?,?)",
            ("waf_fingerprint", category, content, _now()),
        )
        con.commit()
        con.close()
    except Exception:
        pass


# ---------------------------------------------------------------------------
# 1. fingerprint_waf
# ---------------------------------------------------------------------------

def fingerprint_waf(url: str, timeout: int = 8) -> dict:
    """
    Detecte le WAF sur url par analyse des headers et du body des reponses.
    Retourne {"waf": str, "confidence": int, "headers": dict, "signatures": list}.
    """
    result: dict = {"waf": "unknown", "confidence": 0, "headers": {}, "signatures": []}

    session = requests.Session()
    session.headers["User-Agent"] = "CYBERIA-WafDetector/1.0"

    all_headers: dict[str, str] = {}
    bodies: list[str] = []

    # Requete neutre
    try:
        r0 = session.get(url, timeout=timeout, allow_redirects=True)
        all_headers.update({k.lower(): v for k, v in r0.headers.items()})
        bodies.append(r0.text[:4000])
    except Exception:
        pass

    # Requetes de probe (s'arrete au premier blocage)
    for probe in _PROBE_PAYLOADS:
        try:
            probe_url = url.rstrip("/") + "/?q=" + probe
            r = session.get(probe_url, timeout=timeout, allow_redirects=True)
            all_headers.update({k.lower(): v for k, v in r.headers.items()})
            bodies.append(r.text[:4000])
            if r.status_code in (403, 406, 429, 503):
                break
        except Exception:
            continue

    if not bodies:
        return result

    result["headers"] = dict(all_headers)
    combined_body = " ".join(bodies).lower()

    best_name = "unknown"
    best_score = 0
    best_sig: dict = {}

    for sig in WAF_SIGNATURES:
        score = 0
        matched: list[str] = []

        for hk in sig["header_keys"]:
            if hk.lower() in all_headers:
                score += 35
                matched.append(f"header:{hk}")

        for hk, hv in sig["header_values"].items():
            if hv.lower() in all_headers.get(hk.lower(), "").lower():
                score += 30
                matched.append(f"header:{hk}={hv}")

        for bs in sig["body_strings"]:
            if bs.lower() in combined_body:
                score += 25
                matched.append(f"body:{bs}")

        if score > best_score:
            best_score = score
            best_name = sig["name"]
            best_sig = sig
            result["signatures"] = matched

    if best_score > 0:
        base = best_sig.get("confidence_base", 50)
        # chaque tranche de 5 pts au-dessus de 25 ajoute 1 pt de confiance
        bonus = min(20, (best_score - 25) // 5)
        result["confidence"] = min(99, base + bonus)
        result["waf"] = best_name

    return result


# ---------------------------------------------------------------------------
# 2. generate_bypass_prompts
# ---------------------------------------------------------------------------

def generate_bypass_prompts(waf_name: str, category: str) -> dict:
    """
    Construit un prompt MiMo specifique au WAF detecte, l'ecrit dans
    supervisor_prompts.json (ttl=10, priorite=critical) et l'injecte dans
    memory_hub.db.
    Retourne le dict de l'entree creee.
    """
    strategies = WAF_BYPASS_STRATEGIES.get(waf_name, WAF_BYPASS_STRATEGIES["unknown"])
    technique_str = strategies.get(category, strategies.get("xss", ""))
    waf_display = waf_name.upper()

    prompt = (
        f"Generate 8 {category.upper()} payloads specifically designed to bypass {waf_display} WAF rules. "
        f"Focus on: {technique_str}. "
        f"Each payload must evade {waf_display} detection signatures. "
        f"Output JSON only: "
        f"{{\"mutations\":[{{\"payload\":\"...\",\"type\":\"{category}\",\"technique\":\"...\"}}]}}"
    )

    entry = {
        "category": category,
        "prompt": prompt,
        "reason": f"WAF {waf_display} detecte — payloads de bypass specifiques requis.",
        "ttl": 10,
        "priority": "critical",
        "waf_target": waf_name,
        "generated_at": _now(),
    }

    _write_supervisor_prompt(entry)
    _inject_memory(
        category="waf_detection",
        content=f"WAF detecte: {waf_name} | Categorie: {category} | Prompt bypass genere.",
    )
    return entry


# ---------------------------------------------------------------------------
# 3. learn_from_response
# ---------------------------------------------------------------------------

def learn_from_response(
    url: str,
    payload: str,
    status_code: int,
    response_headers: dict,
    waf_name: str,
    payload_type: str = "",
    verdict: str = "",
) -> dict:
    """
    Enregistre le feedback dans waf_feedback.db.
    Si verdict=CONFIRMED : booste le score du payload dans payload_lab.db.
    Retourne {"blocked": bool, "bypass_rate": float, "total": int, "bypassed": int}.
    """
    blocked = 0 if verdict == "CONFIRMED" else (1 if status_code in (403, 406, 429, 503) else 0)

    con = _init_feedback_db()
    con.execute(
        "INSERT INTO feedback (url, payload, waf, blocked, payload_type, timestamp) VALUES (?,?,?,?,?,?)",
        (url, payload, waf_name, blocked, payload_type, _now()),
    )
    con.commit()

    row = con.execute(
        "SELECT COUNT(*), SUM(CASE WHEN blocked=0 THEN 1 ELSE 0 END) FROM feedback WHERE waf=?",
        (waf_name,),
    ).fetchone()
    total = row[0] or 0
    bypassed = int(row[1] or 0)
    bypass_rate = round(bypassed / total * 100, 1) if total > 0 else 0.0
    con.close()

    # Booster le score dans payload_lab.db si bypass confirme
    if blocked == 0 and verdict == "CONFIRMED" and PAYLOAD_LAB_DB.exists():
        try:
            pcon = sqlite3.connect(str(PAYLOAD_LAB_DB), timeout=5)
            pcon.execute(
                "UPDATE results SET score = MIN(score + 10, 100), bypass_confirmed = 1 "
                "WHERE payload = ? AND payload_type LIKE ?",
                (payload, f"%{payload_type}%"),
            )
            pcon.execute(
                "UPDATE imported_payloads SET waf_score = MIN(waf_score + 1, 15) WHERE payload = ?",
                (payload,),
            )
            pcon.commit()
            pcon.close()
        except Exception:
            pass

    return {"blocked": bool(blocked), "bypass_rate": bypass_rate, "total": total, "bypassed": bypassed}


# ---------------------------------------------------------------------------
# 4. get_bypass_stats
# ---------------------------------------------------------------------------

def get_bypass_stats(waf_name: str) -> dict:
    """
    Retourne les statistiques de bypass pour un WAF donne.
    """
    empty = {"waf": waf_name, "total": 0, "bypassed": 0, "bypass_rate": 0.0, "best_payloads": [], "by_type": {}}
    if not WAF_FEEDBACK_DB.exists():
        return empty

    try:
        con = sqlite3.connect(str(WAF_FEEDBACK_DB), timeout=5)

        row = con.execute(
            "SELECT COUNT(*), SUM(CASE WHEN blocked=0 THEN 1 ELSE 0 END) FROM feedback WHERE waf=?",
            (waf_name,),
        ).fetchone()
        total = row[0] or 0
        bypassed = int(row[1] or 0)
        bypass_rate = round(bypassed / total * 100, 1) if total > 0 else 0.0

        best_rows = con.execute(
            "SELECT payload, payload_type FROM feedback WHERE waf=? AND blocked=0 ORDER BY id DESC LIMIT 10",
            (waf_name,),
        ).fetchall()

        type_rows = con.execute(
            "SELECT payload_type, COUNT(*), SUM(CASE WHEN blocked=0 THEN 1 ELSE 0 END) "
            "FROM feedback WHERE waf=? GROUP BY payload_type",
            (waf_name,),
        ).fetchall()
        con.close()
    except Exception:
        return empty

    by_type: dict = {}
    for r in type_rows:
        ptype = r[0] or "unknown"
        t = r[1] or 0
        b = int(r[2] or 0)
        by_type[ptype] = {"total": t, "bypassed": b, "rate": round(b / t * 100, 1) if t > 0 else 0.0}

    return {
        "waf": waf_name,
        "total": total,
        "bypassed": bypassed,
        "bypass_rate": bypass_rate,
        "best_payloads": [{"payload": r[0], "type": r[1]} for r in best_rows],
        "by_type": by_type,
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli() -> None:
    parser = argparse.ArgumentParser(
        description="CYBERIA WAF Fingerprinter",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Exemples:\n"
            "  python core/waf_fingerprint.py --url http://monsite.com\n"
            "  python core/waf_fingerprint.py --url http://monsite.com --category xss --generate-payloads\n"
            "  python core/waf_fingerprint.py --stats cloudflare\n"
        ),
    )
    parser.add_argument("--url", help="URL cible a analyser")
    parser.add_argument("--category", default="xss", help="Categorie de vuln (xss, sqli, lfi, rce, ssti, ssrf)")
    parser.add_argument("--generate-payloads", action="store_true", dest="generate",
                        help="Generer des prompts de bypass dans supervisor_prompts.json")
    parser.add_argument("--stats", metavar="WAF_NAME",
                        help="Afficher les statistiques de bypass pour un WAF")
    args = parser.parse_args()

    if args.stats:
        stats = get_bypass_stats(args.stats)
        print(f"\n=== STATS BYPASS : {stats['waf'].upper()} ===")
        print(f"  Total tests    : {stats['total']}")
        print(f"  Bypasses       : {stats['bypassed']}")
        print(f"  Taux de bypass : {stats['bypass_rate']}%")
        if stats["by_type"]:
            print("\n  Par type :")
            for ptype, d in sorted(stats["by_type"].items()):
                print(f"    {ptype:10s} : {d['bypassed']}/{d['total']} ({d['rate']}%)")
        if stats["best_payloads"]:
            print("\n  Meilleurs payloads :")
            for bp in stats["best_payloads"][:5]:
                print(f"    [{bp['type'] or '?':6s}] {bp['payload'][:70]}")
        return

    if not args.url:
        parser.print_help()
        return

    print(f"\n[*] Fingerprinting WAF sur : {args.url}")
    result = fingerprint_waf(args.url)

    print(f"\n=== RESULTAT ===")
    print(f"  WAF detecte  : {result['waf'].upper()}")
    print(f"  Confiance    : {result['confidence']}%")
    if result["signatures"]:
        print(f"  Signatures   :")
        for s in result["signatures"]:
            print(f"    - {s}")
    interesting_hdrs = {k: v for k, v in result["headers"].items()
                        if any(kw in k for kw in ["cf-", "sucuri", "server", "x-powered", "x-iinfo",
                                                   "akamai", "fortiwa", "barra_", "x-amz"])}
    if interesting_hdrs:
        print(f"  Headers WAF  :")
        for k, v in interesting_hdrs.items():
            print(f"    {k}: {v[:80]}")

    if args.generate:
        cat = args.category
        print(f"\n[*] Generation du prompt [{cat.upper()}] pour {result['waf'].upper()}...")
        entry = generate_bypass_prompts(result["waf"], cat)
        print(f"[+] Ecrit dans supervisor_prompts.json (priorite={entry['priority']}, ttl={entry['ttl']})")
        print(f"[+] Injecte dans memory_hub.db")
        print(f"\n    Prompt : {entry['prompt'][:120]}...")


if __name__ == "__main__":
    _cli()
